[package]
name = "rs-util"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.172"
xcm-rust-common = { path = "../../xcm-rust-common"}
rs-log = { path = "../../libxcm/core/rs-log" }

[lib]
name = "rs_util"
path = "src/util.rs"
crate-type = ["cdylib", "rlib"]