[package]
name = "rs-xcm-dns"
version = "0.1.0"
edition = "2024"

[dependencies]
c2rust-bitfields = "0.20.0"
libc = "0.2.171"
once_cell = "1.21.3"
regex = "1.11.1"

[lib]
path="src/xcm_dns.rs"
crate-type = ["cdylib", "rlib"]
