[package]
name = "rs-common-ctl"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.171"
rs-log = {path="../../libxcm/core/rs-log"}

[lib]
path="src/common_ctl.rs"
crate-type = ["cdylib", "rlib"]