[package]
name = "rs-xcm-tp"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.171"
rs-xcm-addr = {path="../../../core/rs-xcm-addr"}
rs-ctl = {path="../../../ctl/rs-ctl"}

[lib]
path="src/xcm_tp.rs"
crate-type = ["cdylib"]
