[package]
name = "rs-xcm-tp"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.172"
xcm-rust-common = { path = "../../../../xcm-rust-common/" }
rs-attr-node = { path = "../../../core/rs-attr-node"}

[lib]
name = "rs_xcm_tp"
path = "src/xcm_tp.rs"
crate-type = ["cdylib"]

