[package]
name = "rs-xcm_tp"
version = "0.1.0"
edition = "2024"

[lib]
name = "rs_xcm_tp"
path = "src/xcm_tp.rs"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.172"
xcm-rust-common = { path = "../../../../xcm-rust-common/" }
